---
# Requêtes SQL
---

## Q-1 Rating moyen par film :

```sql
SELECT movieId, avg (rating) as 'Moyenne', count (rating) 'Nb votes'
FROM ratings
GROUP BY movieId
ORDER BY avg (rating) DESC, count (rating) DESC
```
![Q1](IMG/Q1.jpg)

**Analyse Q1 :** 

Grâce à cette requête nous pouvons calculer la note moyenne par film et voir le nombre de votants pour chaque film. Ainsi nous pourrons calculer par la suite un indice de popularité qui sera développé en feature. En l’état cette requête seule n’est pas très pertinente, mais nous pouvons quand même repérer les films les mieux notés et en le croisant avec le genre on pourra faire ressortir une statistique intéressante.


---
## Q-2 Quels films n’ont reçus aucun vote ?

```sql 
SELECT movieId,title FROM movies
WHERE movieId
NOT IN (
    SELECT ratings.movieId
    FROM movies
    INNER JOIN ratings
    ON movies.movieId = ratings.movieId)
```
![Q2](IMG/Q2.jpg)
**Analyse Q2 :** 

Grâce à cette requête nous pouvons faire sortir les films sans tags avec leurs identifiants.

---
## Q-3 Combien de personnes différentes ont voté ?

```sql
SELECT count(DISTINCT userId)as 'Nb de Rating'
FROM ratings
```
![Q3](IMG/Q3.jpg)
**Analyse Q3 :** 

Grâce à cette requête nous pouvons faire sortir les films sans tags avec leurs identifiants.

---
## Q-4 Sur combien de films chaque utilisateur a voté ?

```sql
SELECT userId as 'Utilisateurs', count (movieId) as 'Nb de votes'
FROM ratings
GROUP BY userId
ORDER BY count (movieId) DESC
```
![Q4](IMG/Q4.jpg)
**Analyse Q4 :** 

Grâce à cette requête nous pouvons faire sortir les films sans tags avec leurs identifiants.

---
## Q-5 Quels sont les genres les plus représentés ? 

```sql
SELECT DISTINCT substr(genres, 1, 5)
FROM movies
```
![Q5](IMG/Q5.jpg)
**Analyse Q5 :** 

Grâce à cette requête nous pouvons faire sortir les films sans tags avec leurs identifiants.

---
## Q-6 Quels sont les genres les mieux notés ?

```sql
SELECT tag, count(tag) AS cTag
FROM tags
GROUP BY tag
ORDER BY cTag DESC
```
![Q6](IMG/Q6.jpg)
**Analyse Q6 :** 

Grâce à cette requête nous pouvons faire sortir les films sans tags avec leurs identifiants.

---
## Q-7 Quels sont les films sans tag ?

```sql
SELECT movieId,title 
FROM movies
WHERE movieId
NOT IN (
    SELECT tags.movieId
    FROM movies
    INNER JOIN tags
    ON movies.movieId = tags.movieId)
```
![Q7](IMG/Q7.jpg)

**Analyse Q7 :** 

Grâce à cette requête nous pouvons faire sortir les films sans tags avec leurs identifiants.